name: Enjektor-Yapici
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Exe-Derle
        run: g++ -o KebapEnjektor.exe enjektor.cpp -static
      - name: Dosyayi-Ver
        uses: actions/upload-artifact@v4
        with:
          name: Kebap-Enjektor-Exe
          path: KebapEnjektor.exe
